// Code generated by protoc-gen-go-setters. DO NOT EDIT.
// source: example/sample.proto
package example

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// SetUserId will set User.UserId.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) SetUserId(in string) {
	x.UserId = in
}

// SetDisplayName will set User.DisplayName.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) SetDisplayName(in string) {
	x.DisplayName = in
}

// SetVerified will set User.Verified.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) SetVerified(in bool) {
	x.Verified = in
}

// SetCreateTime will set User.CreateTime.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) SetCreateTime(in *timestamppb.Timestamp) {
	x.CreateTime = in
}

// SetPostCount will set User.PostCount.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) SetPostCount(in int32) {
	x.PostCount = in
}

// SetInterests will set User.Interests.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) SetInterests(in []string) {
	x.Interests = in
}

// AppendInterests will append all input values to User.Interests.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) AppendInterests(in ...string) {
	x.Interests = append(x.Interests, in...)
}

// SetMembership will set User.Membership.
//
// WARNING: no nil checks are performed on the parent message.
func (x *User) SetMembership(in MembershipType) {
	x.Membership = in
}

// SetPageSize will set ListUsersRequest.PageSize.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListUsersRequest) SetPageSize(in int32) {
	x.PageSize = in
}

// SetTagFilters will set ListUsersRequest.TagFilters.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListUsersRequest) SetTagFilters(in []string) {
	x.TagFilters = in
}

// AppendTagFilters will append all input values to ListUsersRequest.TagFilters.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListUsersRequest) AppendTagFilters(in ...string) {
	x.TagFilters = append(x.TagFilters, in...)
}

// SetPageToken will set ListUsersRequest.PageToken.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListUsersRequest) SetPageToken(in string) {
	x.PageToken = in
}

// SetUsers will set ListUsersResponse.Users.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListUsersResponse) SetUsers(in []*User) {
	x.Users = in
}

// AppendUsers will append all input values to ListUsersResponse.Users.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListUsersResponse) AppendUsers(in ...*User) {
	x.Users = append(x.Users, in...)
}

// SetNextPageToken will set ListUsersResponse.NextPageToken.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListUsersResponse) SetNextPageToken(in string) {
	x.NextPageToken = in
}

// SetPageSize will set ListPostsRequest.PageSize.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListPostsRequest) SetPageSize(in int32) {
	x.PageSize = in
}

// SetTagFilters will set ListPostsRequest.TagFilters.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListPostsRequest) SetTagFilters(in []string) {
	x.TagFilters = in
}

// AppendTagFilters will append all input values to ListPostsRequest.TagFilters.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListPostsRequest) AppendTagFilters(in ...string) {
	x.TagFilters = append(x.TagFilters, in...)
}

// SetPageToken will set ListPostsRequest.PageToken.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListPostsRequest) SetPageToken(in string) {
	x.PageToken = in
}

// SetPosts will set ListPostsResponse.Posts.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListPostsResponse) SetPosts(in []*Post) {
	x.Posts = in
}

// AppendPosts will append all input values to ListPostsResponse.Posts.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListPostsResponse) AppendPosts(in ...*Post) {
	x.Posts = append(x.Posts, in...)
}

// SetNextPageToken will set ListPostsResponse.NextPageToken.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListPostsResponse) SetNextPageToken(in string) {
	x.NextPageToken = in
}

// SetPost will set CreatePostRequest.Post.
//
// WARNING: no nil checks are performed on the parent message.
func (x *CreatePostRequest) SetPost(in *Post) {
	x.Post = in
}

// SetAudio will set Post.Audio to input.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Post) SetAudio(in *Audio) {
	x.PostContent = &Post_Audio{Audio: in}
}

// SetVideo will set Post.Video to input.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Post) SetVideo(in *Video) {
	x.PostContent = &Post_Video{Video: in}
}

// SetText will set Post.Text to input.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Post) SetText(in string) {
	x.PostContent = &Post_Text{Text: in}
}

// SetAuthorId will set Post.AuthorId.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Post) SetAuthorId(in string) {
	x.AuthorId = in
}

// SetTitle will set Post.Title.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Post) SetTitle(in string) {
	x.Title = in
}
