// Code generated by protoc-gen-go-setters. DO NOT EDIT.
// source: example/speakers.proto
package example

// SetPageSize will set ListSpeakersRequest.PageSize.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListSpeakersRequest) SetPageSize(in int32) {
	x.PageSize = in
}

// SetSpeakerName will set ListSpeakersRequest.SpeakerName.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListSpeakersRequest) SetSpeakerName(in string) {
	x.SpeakerName = in
}

// SetSpeakers will set ListSpeakersResponse.Speakers.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListSpeakersResponse) SetSpeakers(in []*Speaker) {
	x.Speakers = in
}

// AppendSpeakers will append all input values to ListSpeakersResponse.Speakers.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListSpeakersResponse) AppendSpeakers(in ...*Speaker) {
	x.Speakers = append(x.Speakers, in...)
}

// SetNextPageToken will set ListSpeakersResponse.NextPageToken.
//
// WARNING: no nil checks are performed on the parent message.
func (x *ListSpeakersResponse) SetNextPageToken(in string) {
	x.NextPageToken = in
}

// SetSpeaker will set CreateSpeakerRequest.Speaker.
//
// WARNING: no nil checks are performed on the parent message.
func (x *CreateSpeakerRequest) SetSpeaker(in *Speaker) {
	x.Speaker = in
}

// SetSpeakerId will set Speaker.SpeakerId.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Speaker) SetSpeakerId(in string) {
	x.SpeakerId = in
}

// SetDisplayName will set Speaker.DisplayName.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Speaker) SetDisplayName(in string) {
	x.DisplayName = in
}

// SetApproved will set Speaker.Approved.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Speaker) SetApproved(in bool) {
	x.Approved = in
}

// SetTalks will set Speaker.Talks.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Speaker) SetTalks(in []string) {
	x.Talks = in
}

// AppendTalks will append all input values to Speaker.Talks.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Speaker) AppendTalks(in ...string) {
	x.Talks = append(x.Talks, in...)
}

// SetGithubUrl will set Speaker.GithubUrl.
//
// WARNING: no nil checks are performed on the parent message.
func (x *Speaker) SetGithubUrl(in *string) {
	x.GithubUrl = in
}
