// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: example/talk.proto

package example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TalkServiceClient is the client API for TalkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TalkServiceClient interface {
	// ListTalks is used to get all talks according to any provided query params within ListTalksRequest
	ListTalks(ctx context.Context, in *ListTalksRequest, opts ...grpc.CallOption) (*ListTalksResponse, error)
	// ListTalks is used to get all talks according to any provided query params within ListTalksRequest
	CreateTalks(ctx context.Context, in *CreateTalksRequest, opts ...grpc.CallOption) (*Talk, error)
}

type talkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTalkServiceClient(cc grpc.ClientConnInterface) TalkServiceClient {
	return &talkServiceClient{cc}
}

func (c *talkServiceClient) ListTalks(ctx context.Context, in *ListTalksRequest, opts ...grpc.CallOption) (*ListTalksResponse, error) {
	out := new(ListTalksResponse)
	err := c.cc.Invoke(ctx, "/example.TalkService/ListTalks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talkServiceClient) CreateTalks(ctx context.Context, in *CreateTalksRequest, opts ...grpc.CallOption) (*Talk, error) {
	out := new(Talk)
	err := c.cc.Invoke(ctx, "/example.TalkService/CreateTalks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalkServiceServer is the server API for TalkService service.
// All implementations must embed UnimplementedTalkServiceServer
// for forward compatibility
type TalkServiceServer interface {
	// ListTalks is used to get all talks according to any provided query params within ListTalksRequest
	ListTalks(context.Context, *ListTalksRequest) (*ListTalksResponse, error)
	// ListTalks is used to get all talks according to any provided query params within ListTalksRequest
	CreateTalks(context.Context, *CreateTalksRequest) (*Talk, error)
	mustEmbedUnimplementedTalkServiceServer()
}

// UnimplementedTalkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTalkServiceServer struct {
}

func (UnimplementedTalkServiceServer) ListTalks(context.Context, *ListTalksRequest) (*ListTalksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTalks not implemented")
}
func (UnimplementedTalkServiceServer) CreateTalks(context.Context, *CreateTalksRequest) (*Talk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTalks not implemented")
}
func (UnimplementedTalkServiceServer) mustEmbedUnimplementedTalkServiceServer() {}

// UnsafeTalkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TalkServiceServer will
// result in compilation errors.
type UnsafeTalkServiceServer interface {
	mustEmbedUnimplementedTalkServiceServer()
}

func RegisterTalkServiceServer(s grpc.ServiceRegistrar, srv TalkServiceServer) {
	s.RegisterService(&TalkService_ServiceDesc, srv)
}

func _TalkService_ListTalks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTalksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).ListTalks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.TalkService/ListTalks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).ListTalks(ctx, req.(*ListTalksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalkService_CreateTalks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTalksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalkServiceServer).CreateTalks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.TalkService/CreateTalks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalkServiceServer).CreateTalks(ctx, req.(*CreateTalksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TalkService_ServiceDesc is the grpc.ServiceDesc for TalkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TalkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.TalkService",
	HandlerType: (*TalkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTalks",
			Handler:    _TalkService_ListTalks_Handler,
		},
		{
			MethodName: "CreateTalks",
			Handler:    _TalkService_CreateTalks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/talk.proto",
}
