// Code generated by protoc-gen-go-setters. DO NOT EDIT.
// source: proto/sample.proto
package protoc_gen_go

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (x *User) SetUserId(in string) {
	x.UserId = in
}

func (x *User) SetDisplayName(in string) {
	x.DisplayName = in
}

func (x *User) SetVerified(in bool) {
	x.Verified = in
}

func (x *User) SetCreateTime(in *timestamppb.Timestamp) {
	x.CreateTime = in
}

func (x *User) SetPostCount(in int32) {
	x.PostCount = in
}

func (x *User) SetInterests(in []string) {
	x.Interests = in
}

func (x *User) AppendInterests(in ...string) {
	x.Interests = append(x.Interests, in...)
}

func (x *User) SetMembership(in MembershipType) {
	x.Membership = in
}

func (x *ListPostsRequest) SetPageSize(in int32) {
	x.PageSize = in
}

func (x *ListPostsRequest) SetTagFilters(in []string) {
	x.TagFilters = in
}

func (x *ListPostsRequest) AppendTagFilters(in ...string) {
	x.TagFilters = append(x.TagFilters, in...)
}

func (x *ListPostsRequest) SetPageToken(in string) {
	x.PageToken = in
}

func (x *ListPostsResponse) SetPosts(in []*Post) {
	x.Posts = in
}

func (x *ListPostsResponse) AppendPosts(in ...*Post) {
	x.Posts = append(x.Posts, in...)
}

func (x *ListPostsResponse) SetNextPagaeToken(in string) {
	x.NextPagaeToken = in
}

func (x *CreatePostRequest) SetPost(in *Post) {
	x.Post = in
}

func (x *Post) SetAudio(in *Audio) {
	x.PostContent = &Post_Audio{Audio: in}
}

func (x *Post) SetVideo(in *Video) {
	x.PostContent = &Post_Video{Video: in}
}

func (x *Post) SetText(in string) {
	x.PostContent = &Post_Text{Text: in}
}

func (x *Post) SetAuthorId(in string) {
	x.AuthorId = in
}

func (x *Post) SetTitle(in string) {
	x.Title = in
}
